import jsPDF from 'jspdf';

export function generateATSReportPDF(resume) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // ── Header / Branding ──
  doc.setFillColor(99, 102, 241); // #6366f1
  doc.rect(0, 0, pageWidth, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont(undefined, 'bold');
  doc.text('PathFinder', 14, 15);
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.text('AI-Powered ATS Resume Report', 14, 24);

  y = 48;

  // ── Filename + Date ──
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text(`Resume: ${resume.filename}`, 14, y);
  doc.setFont(undefined, 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}`, 14, y + 6);

  y += 20;

  // ── Overall Score (big circle-ish box) ──
  const scoreColor = resume.atsScore >= 75 ? [34, 197, 94] : resume.atsScore >= 50 ? [245, 158, 11] : [239, 68, 68];
  doc.setDrawColor(...scoreColor);
  doc.setLineWidth(1.5);
  doc.roundedRect(14, y, pageWidth - 28, 30, 3, 3, 'S');
  doc.setFontSize(28);
  doc.setTextColor(...scoreColor);
  doc.setFont(undefined, 'bold');
  doc.text(`${resume.atsScore}/100`, 20, y + 20);
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.setFont(undefined, 'normal');
  doc.text('Overall ATS Score', pageWidth - 70, y + 18);

  y += 42;

  // ── Section: Score Breakdown ──
  doc.setFontSize(13);
  doc.setTextColor(30, 41, 59);
  doc.setFont(undefined, 'bold');
  doc.text('Score Breakdown', 14, y);
  y += 8;

  const breakdown = resume.breakdown || {};
  const rows = [
    ['Keyword Match', breakdown.keywordMatch],
    ['Formatting', breakdown.formatting],
    ['Skills Relevance', breakdown.skillsRelevance],
    ['Experience Match', breakdown.experienceMatch],
  ];

  rows.forEach(([label, score]) => {
    const val = score ?? 0;
    const barColor = val >= 75 ? [34, 197, 94] : val >= 50 ? [245, 158, 11] : [239, 68, 68];

    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.setFont(undefined, 'normal');
    doc.text(label, 14, y);
    doc.text(`${val}%`, pageWidth - 24, y);

    // Progress bar background
    doc.setFillColor(226, 232, 240);
    doc.roundedRect(14, y + 2, pageWidth - 28, 3, 1.5, 1.5, 'F');
    // Progress bar fill
    doc.setFillColor(...barColor);
    const barWidth = ((pageWidth - 28) * val) / 100;
    if (barWidth > 0) doc.roundedRect(14, y + 2, barWidth, 3, 1.5, 1.5, 'F');

    y += 12;
  });

  y += 6;

  // ── Section: Strengths ──
  if (resume.strengths?.length) {
    doc.setFontSize(13);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(34, 197, 94);
    doc.text('Strengths', 14, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(30, 41, 59);
    resume.strengths.forEach(s => {
      const lines = doc.splitTextToSize(`• ${s}`, pageWidth - 28);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 2;
    });
    y += 4;
  }

  // ── Section: Missing Skills ──
  if (resume.missingSkills?.length) {
    checkPageBreak();
    doc.setFontSize(13);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(239, 68, 68);
    doc.text('Missing Skills', 14, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(30, 41, 59);
    const skillsText = resume.missingSkills.join('   •   ');
    const lines = doc.splitTextToSize(skillsText, pageWidth - 28);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 10;
  }

  // ── Section: Suggestions ──
  if (resume.suggestions?.length) {
    checkPageBreak();
    doc.setFontSize(13);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(99, 102, 241);
    doc.text('Suggestions for Improvement', 14, y);
    y += 7;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.setTextColor(30, 41, 59);
    resume.suggestions.forEach((s, i) => {
      checkPageBreak();
      const lines = doc.splitTextToSize(`${i + 1}. ${s}`, pageWidth - 28);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 3;
    });
  }

  // Helper for page breaks
  function checkPageBreak() {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  }

  // ── Footer ──
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by PathFinder AI Career Coach', 14, 290);
  }

  doc.save(`ATS_Report_${resume.filename.replace(/\.[^/.]+$/, '')}.pdf`);
}